Repository thunderbird/thunderbird-android, pull requests merged in 2024-02, with the labels that each got.

#7590 Translations update from Hosted Weblate
  app/ui/base/src/main/res/values-enm/strings.xml
  app/ui/legacy/src/main/res/values-ar/strings.xml
  app/ui/legacy/src/main/res/values-enm/strings.xml
  app/ui/legacy/src/main/res/values-fr/strings.xml
  app/ui/legacy/src/main/res/values-ta-rIN/strings.xml
  app/ui/legacy/src/main/res/values-zh-rCN/strings.xml
  core/ui/compose/designsystem/src/main/res/values-enm/strings.xml
  feature/account/common/src/main/res/values-enm/strings.xml
  feature/account/common/src/main/res/values-pt-rBR/strings.xml
  feature/account/common/src/main/res/values-pt-rPT/strings.xml
  feature/account/oauth/src/main/res/values-enm/strings.xml
  feature/account/server/certificate/src/main/res/values-enm/strings.xml
  feature/account/server/certificate/src/main/res/values-pt-rPT/strings.xml
  feature/account/server/settings/src/main/res/values-enm/strings.xml
  feature/account/server/settings/src/main/res/values-pt-rBR/strings.xml
  feature/account/server/validation/src/main/res/values-enm/strings.xml
  feature/account/server/validation/src/main/res/values-es/strings.xml
  feature/account/server/validation/src/main/res/values-fr/strings.xml
  feature/account/server/validation/src/main/res/values-pt-rBR/strings.xml
  feature/account/server/validation/src/main/res/values-pt-rPT/strings.xml
  feature/account/server/validation/src/main/res/values-sv/strings.xml
  feature/account/setup/src/main/res/values-enm/strings.xml
  feature/account/setup/src/main/res/values-et/strings.xml
  feature/account/setup/src/main/res/values-fr/strings.xml
  feature/account/setup/src/main/res/values-fy/strings.xml
  feature/account/setup/src/main/res/values-nl/strings.xml
  feature/account/setup/src/main/res/values-pl/strings.xml
  feature/account/setup/src/main/res/values-pt-rPT/strings.xml
  feature/account/setup/src/main/res/values-sv/strings.xml
  feature/account/setup/src/main/res/values-tr/strings.xml
  feature/account/setup/src/main/res/values-zh-rCN/strings.xml
  feature/onboarding/permissions/src/main/res/values-enm/strings.xml
  feature/onboarding/welcome/src/main/res/values-enm/strings.xml
  feature/settings/import/src/main/res/values-enm/strings.xml
  feature/settings/import/src/main/res/values-fr/strings.xml
  feature/settings/import/src/main/res/values-ka/strings.xml
Labels: type: translation

#7638 Add translation cli
  app-k9mail/build.gradle.kts
  app/core/src/main/res/values/arrays_general_settings_values.xml
  cli/translation-cli/README.md
  cli/translation-cli/build.gradle.kts
  cli/translation-cli/src/main/kotlin/net/thunderbird/cli/translation/LanguageCodeLoader.kt
  cli/translation-cli/src/main/kotlin/net/thunderbird/cli/translation/Main.kt
  cli/translation-cli/src/main/kotlin/net/thunderbird/cli/translation/ResourceConfigurationsFormatter.kt
  cli/translation-cli/src/main/kotlin/net/thunderbird/cli/translation/SupportedLanguagesFormatter.kt
  cli/translation-cli/src/main/kotlin/net/thunderbird/cli/translation/TranslationCli.kt
  cli/translation-cli/src/main/kotlin/net/thunderbird/cli/translation/net/Language.kt
  cli/translation-cli/src/main/kotlin/net/thunderbird/cli/translation/net/TranslationResponse.kt
  cli/translation-cli/src/main/kotlin/net/thunderbird/cli/translation/net/WeblateClient.kt
  cli/translation-cli/src/main/kotlin/net/thunderbird/cli/translation/net/WeblateConfig.kt
  gradle/libs.versions.toml
  scripts/autodiscovery
  scripts/debian_build.sh
  scripts/html-cleaner
  scripts/translation
  settings.gradle.kts
Labels: type: enhancement

#7660 Update dependencies
  app-k9mail/dependencies/releaseRuntimeClasspath.txt
  app/storage/src/test/java/com/fsck/k9/storage/messages/MessagePartDatabaseHelpers.kt
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: type: dependency

#7661 Replace Accompanist Systemuicontroller with edge-to-edge
  app-k9mail/dependencies/releaseRuntimeClasspath.txt
  core/ui/compose/theme/build.gradle.kts
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/MainTheme.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/color/SystemBarsColor.kt
  feature/launcher/src/main/kotlin/app/k9mail/feature/launcher/FeatureLauncherActivity.kt
  gradle/libs.versions.toml
Labels: type: dependency

#7667 Move `html-cleaner` from app namspace to library
  app/core/build.gradle.kts
  cli/html-cleaner-cli/build.gradle.kts
  library/html-cleaner/build.gradle.kts
  library/html-cleaner/src/main/kotlin/app/k9mail/html/cleaner/BodyCleaner.kt
  library/html-cleaner/src/main/kotlin/app/k9mail/html/cleaner/HeadCleaner.kt
  library/html-cleaner/src/main/kotlin/app/k9mail/html/cleaner/HtmlHeadProvider.kt
  library/html-cleaner/src/main/kotlin/app/k9mail/html/cleaner/HtmlProcessor.kt
  library/html-cleaner/src/main/kotlin/app/k9mail/html/cleaner/HtmlSanitizer.kt
  library/html-cleaner/src/test/kotlin/app/k9mail/html/cleaner/HtmlSanitizerTest.kt
  settings.gradle.kts
Labels: type: architecture

#7664 Update dependencies
  app-k9mail/dependencies/releaseRuntimeClasspath.txt
  build-plugin/build.gradle.kts
  build-plugin/src/main/kotlin/thunderbird.app.android.gradle.kts
  build-plugin/src/main/kotlin/thunderbird.app.jvm.gradle.kts
  build-plugin/src/main/kotlin/thunderbird.library.android.gradle.kts
  build-plugin/src/main/kotlin/thunderbird.library.jvm.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: type: dependency
