Repository thunderbird/thunderbird-android, pull requests merged in 2024-04, with the labels that each got.

#7743 Add `FOREGROUND_SERVICE_DATA_SYNC` permission to manifest
  app/common/src/main/AndroidManifest.xml
Labels: task: backport

#7742 Add support for background activity start mode (Android 14)
  app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageCompose.java
  app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageList.kt
  app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageLoaderHelper.java
  app/ui/legacy/src/main/java/com/fsck/k9/ui/crypto/MessageCryptoCallback.java
  app/ui/legacy/src/main/java/com/fsck/k9/ui/crypto/MessageCryptoHelper.java
  app/ui/legacy/src/main/java/com/fsck/k9/ui/endtoend/AutocryptKeyTransferActivity.kt
  app/ui/legacy/src/main/java/com/fsck/k9/ui/messagedetails/MessageDetailsFragment.kt
  app/ui/legacy/src/main/java/com/fsck/k9/ui/messageview/MessageCryptoPresenter.java
  app/ui/legacy/src/main/java/com/fsck/k9/ui/messageview/MessageViewContainerFragment.kt
  app/ui/legacy/src/main/java/com/fsck/k9/ui/messageview/MessageViewFragment.kt
  plugins/openpgp-api-lib/openpgp-api/src/main/java/org/openintents/openpgp/util/OpenPgpIntentStarter.kt
  plugins/openpgp-api-lib/openpgp-api/src/main/java/org/openintents/openpgp/util/OpenPgpKeyPreference.java
Labels: task: backport

#7760 Dependency updates
  app-k9mail/dependencies/releaseRuntimeClasspath.txt
  build-plugin/src/main/kotlin/thunderbird.app.android.gradle.kts
  build-plugin/src/main/kotlin/thunderbird.app.jvm.gradle.kts
  build-plugin/src/main/kotlin/thunderbird.library.android.gradle.kts
  build-plugin/src/main/kotlin/thunderbird.library.jvm.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: type: dependency

#7772 Fix `Context.registerReceiver()` calls to specify export behavior
  app/core/src/main/java/com/fsck/k9/controller/push/AutoSyncManager.kt
  app/core/src/main/java/com/fsck/k9/provider/AttachmentTempFileProvider.java
  app/core/src/main/java/com/fsck/k9/provider/DecryptedFileProvider.java
Labels: task: backport

#7771 Remove Material 2 text atoms
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/ui/atom/items/ColorItems.kt
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/ui/atom/items/IconItems.kt
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/ui/atom/items/ImageItems.kt
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/ui/atom/items/SelectionControlItems.kt
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/ui/atom/items/TextFieldItems.kt
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/ui/atom/items/TypographyItems.kt
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/ui/common/drawer/DrawerCategoryItem.kt
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/ui/common/drawer/DrawerHeaderItem.kt
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/ui/common/list/SectionHeaderItem.kt
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/ui/common/list/SectionInfoItem.kt
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/ui/common/list/SectionSubtitleItem.kt
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/ui/molecule/items/StateItems.kt
  core/ui/compose/common/src/test/kotlin/app/k9mail/core/ui/compose/common/koin/KoinPreviewTest.kt
  core/ui/compose/designsystem/build.gradle.kts
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextBody1.kt
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextBody2.kt
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextButton.kt
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextCaption.kt
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextHeadline1.kt
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextHeadline2.kt
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextHeadline3.kt
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextHeadline4.kt
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextHeadline5.kt
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextHeadline6.kt
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextOverline.kt
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextSubtitle1.kt
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/atom/text/TextSubtitle2.kt
  feature/account/common/src/main/kotlin/app/k9mail/feature/account/common/ui/AppTitleTopHeader.kt
  feature/account/common/src/main/kotlin/app/k9mail/feature/account/common/ui/ContentListView.kt
  feature/account/common/src/main/kotlin/app/k9mail/feature/account/common/ui/view/SuccessView.kt
  feature/account/oauth/src/main/kotlin/app/k9mail/feature/account/oauth/ui/view/SignInView.kt
  feature/account/oauth/src/test/kotlin/app/k9mail/feature/account/oauth/ui/AccountOAuthViewKtTest.kt
  feature/account/server/certificate/src/main/kotlin/app/k9mail/feature/account/server/certificate/ui/ServerCertificateErrorContent.kt
  feature/account/server/certificate/src/main/kotlin/app/k9mail/feature/account/server/certificate/ui/ServerCertificateView.kt
  feature/account/server/validation/src/main/kotlin/app/k9mail/feature/account/server/validation/ui/ServerValidationContent.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/view/AutoDiscoveryResultBodyView.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/view/AutoDiscoveryResultHeaderView.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/view/AutoDiscoveryServerSettingsView.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/options/display/DisplayOptionsContent.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/options/sync/SyncOptionsContent.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/specialfolders/SpecialFoldersFormContent.kt
  feature/account/setup/src/test/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryScreenKtTest.kt
  feature/account/setup/src/test/kotlin/app/k9mail/feature/account/setup/ui/options/display/DisplayOptionsScreenKtTest.kt
  feature/account/setup/src/test/kotlin/app/k9mail/feature/account/setup/ui/options/sync/SyncOptionsScreenKtTest.kt
  feature/onboarding/permissions/src/main/kotlin/app/k9mail/feature/onboarding/permissions/ui/PermissionBox.kt
  feature/onboarding/permissions/src/main/kotlin/app/k9mail/feature/onboarding/permissions/ui/PermissionsContent.kt
  feature/onboarding/welcome/src/main/kotlin/app/k9mail/feature/onboarding/welcome/ui/WelcomeContent.kt
Labels: type: UI/UX

#7778 Set `targetSdkVersion` to 34
  build-plugin/src/main/kotlin/ThunderbirdProjectConfig.kt
Labels: task: backport

#7786 Change features to theme 2 - part 4
  feature/account/common/src/main/kotlin/app/k9mail/feature/account/common/ui/preview/PreviewAccountStateRepository.kt
  feature/account/oauth/src/debug/kotlin/app/k9mail/feature/account/oauth/ui/fake/FakeAccountOAuthViewModel.kt
  feature/account/oauth/src/main/kotlin/app/k9mail/feature/account/oauth/ui/preview/PreviewAccountOAuthViewModel.kt
  feature/account/server/settings/src/debug/kotlin/app/k9mail/feature/account/server/settings/ui/common/ServerSettingsPasswordInputPreview.kt
  feature/account/server/settings/src/main/kotlin/app/k9mail/feature/account/server/settings/ui/incoming/IncomingServerSettingsContent.kt
  feature/account/server/settings/src/main/kotlin/app/k9mail/feature/account/server/settings/ui/incoming/content/IncomingFormItems.kt
  feature/account/server/settings/src/main/kotlin/app/k9mail/feature/account/server/settings/ui/outgoing/OutgoingServerSettingsContent.kt
  feature/account/server/settings/src/main/kotlin/app/k9mail/feature/account/server/settings/ui/outgoing/OutgoingServerSettingsScreen.kt
  feature/account/server/settings/src/main/kotlin/app/k9mail/feature/account/server/settings/ui/outgoing/content/OutgoingFormItems.kt
  feature/account/setup/src/debug/kotlin/app/k9mail/feature/account/setup/ui/autodiscovery/AccountAutoDiscoveryContentPreview.kt
  feature/account/setup/src/debug/kotlin/app/k9mail/feature/account/setup/ui/createaccount/CreateAccountContentPreview.kt
  feature/account/setup/src/debug/kotlin/app/k9mail/feature/account/setup/ui/createaccount/CreateAccountScreenPreview.kt
  feature/account/setup/src/debug/kotlin/app/k9mail/feature/account/setup/ui/options/display/DisplayOptionsContentPreview.kt
  feature/account/setup/src/debug/kotlin/app/k9mail/feature/account/setup/ui/options/display/DisplayOptionsScreenPreview.kt
  feature/account/setup/src/debug/kotlin/app/k9mail/feature/account/setup/ui/options/sync/SyncOptionsContentPreview.kt
  feature/account/setup/src/debug/kotlin/app/k9mail/feature/account/setup/ui/options/sync/SyncOptionsScreenPreview.kt
  feature/account/setup/src/debug/kotlin/app/k9mail/feature/account/setup/ui/specialfolders/SpecialFoldersContentPreview.kt
  feature/account/setup/src/debug/kotlin/app/k9mail/feature/account/setup/ui/specialfolders/SpecialFoldersFormContentPreview.kt
  feature/account/setup/src/debug/kotlin/app/k9mail/feature/account/setup/ui/specialfolders/SpecialFoldersScreenPreview.kt
  feature/account/setup/src/debug/kotlin/app/k9mail/feature/account/setup/ui/specialfolders/fake/FakeSpecialFoldersViewModel.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/createaccount/CreateAccountScreen.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/options/display/DisplayOptionsContent.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/options/display/DisplayOptionsScreen.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/options/sync/SyncOptionsContent.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/options/sync/SyncOptionsScreen.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/specialfolders/SpecialFoldersContent.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/specialfolders/SpecialFoldersFormContent.kt
  feature/account/setup/src/main/kotlin/app/k9mail/feature/account/setup/ui/specialfolders/SpecialFoldersScreen.kt
  feature/account/setup/src/test/kotlin/app/k9mail/feature/account/setup/ui/specialfolders/FakeSpecialFoldersFormUiModel.kt
  feature/account/setup/src/test/kotlin/app/k9mail/feature/account/setup/ui/specialfolders/SpecialFoldersViewModelTest.kt
  feature/launcher/src/main/kotlin/app/k9mail/feature/launcher/ui/FeatureLauncherApp.kt
Labels: type: UI/UX

#7788 Remove Material 2 theme
  app-k9mail/dependencies/releaseRuntimeClasspath.txt
  app-thunderbird/dependencies/releaseRuntimeClasspath.txt
  core/ui/compose/designsystem/build.gradle.kts
  core/ui/compose/designsystem/src/debug/kotlin/app/k9mail/core/ui/compose/designsystem/PreviewWithThemes.kt
  core/ui/compose/testing/build.gradle.kts
  core/ui/compose/testing/src/main/kotlin/app/k9mail/core/ui/compose/testing/ComposeTest.kt
  core/ui/compose/theme/README.md
  core/ui/compose/theme/build.gradle.kts
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/Elevations.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/Images.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/K9Theme.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/MainTheme.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/PreviewWithThemes.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/Shapes.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/Sizes.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/Spacings.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/ThunderbirdTheme.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/Typography.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/color/Colors.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/color/MaterialColor.kt
  core/ui/compose/theme/src/main/java/app/k9mail/core/ui/compose/theme/color/SystemBarsColor.kt
  core/ui/compose/theme/src/main/res/drawable/core_ui_theme_k9_logo.xml
  core/ui/compose/theme/src/main/res/drawable/core_ui_theme_thunderbird_logo.xml
  feature/account/oauth/build.gradle.kts
  feature/account/oauth/src/main/kotlin/app/k9mail/feature/account/oauth/ui/view/SignInWithGoogleButton.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: type: UI/UX

#7798 Change K9 theme to 0.2.0
  app-ui-catalog/src/main/java/app/k9mail/ui/catalog/CatalogActivity.kt
  app/core/src/main/res/values/k9_tonal_palette.xml
  app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageList.kt
  app/ui/legacy/src/main/res/layout/message_compose_content.xml
  app/ui/legacy/src/main/res/layout/message_compose_recipients.xml
  app/ui/legacy/src/main/res/values-v23/themes.xml
  app/ui/legacy/src/main/res/values-v27/themes.xml
  app/ui/legacy/src/main/res/values/styles.xml
  app/ui/legacy/src/main/res/values/themes.xml
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/organism/TopAppBar.kt
  core/ui/compose/theme2/common/src/main/kotlin/app/k9mail/core/ui/compose/theme2/SystemBar.kt
  core/ui/compose/theme2/k9mail/src/main/kotlin/app/k9mail/core/ui/compose/theme2/k9mail/TonalColorPalette.kt
Labels: type: UI/UX

#7799 Fix `ResponsiveContentWithSurface` to use the correct surface color
  core/ui/compose/designsystem/src/main/kotlin/app/k9mail/core/ui/compose/designsystem/template/ResponsiveContentWithSurface.kt
Labels: type: UI/UX
