Repository thunderbird/thunderbird-android, pull requests merged in 2024-12, with the labels that each got.

#8582 Publish to FTP
  .github/workflows/shippable_builds.yml
  scripts/setup_release_automation
Labels: task: uplift to beta

#8653 Add id-token permissions to daily build
  .github/workflows/daily_builds.yml
Labels: task: uplift to beta

#8657 Translations update from Hosted Weblate
  app-metadata/com.fsck.k9/sv-SE/short_description.txt
  app-metadata/net.thunderbird.android.beta/sr/full_description.txt
  app-metadata/net.thunderbird.android.beta/sr/short_description.txt
  app-metadata/net.thunderbird.android.beta/sr/title.txt
  app-metadata/net.thunderbird.android.beta/vi/short_description.txt
  app-metadata/net.thunderbird.android.beta/vi/title.txt
  app-metadata/net.thunderbird.android/sr/short_description.txt
  app-metadata/net.thunderbird.android/sr/title.txt
  app-metadata/net.thunderbird.android/vi/short_description.txt
  app-metadata/net.thunderbird.android/vi/title.txt
  feature/account/common/src/main/res/values-sq/strings.xml
  feature/account/edit/src/main/res/values-vi/strings.xml
  feature/account/oauth/src/main/res/values-ja/strings.xml
  feature/account/oauth/src/main/res/values-ro/strings.xml
  feature/account/oauth/src/main/res/values-sr/strings.xml
  feature/account/oauth/src/main/res/values-vi/strings.xml
  feature/account/server/validation/src/main/res/values-sq/strings.xml
  feature/account/setup/src/main/res/values-vi/strings.xml
  feature/funding/googleplay/src/main/res/values-co/strings.xml
  feature/funding/googleplay/src/main/res/values-ja/strings.xml
  feature/funding/googleplay/src/main/res/values-pt-rBR/strings.xml
  feature/funding/googleplay/src/main/res/values-sq/strings.xml
  feature/funding/googleplay/src/main/res/values-sr/strings.xml
  feature/funding/googleplay/src/main/res/values-vi/strings.xml
  feature/migration/qrcode/src/main/res/values-sr/strings.xml
  feature/migration/qrcode/src/main/res/values-vi/strings.xml
  feature/navigation/drawer/src/main/res/values-sr/strings.xml
  feature/navigation/drawer/src/main/res/values-vi/strings.xml
  feature/onboarding/migration/thunderbird/src/main/res/values-co/strings.xml
  feature/onboarding/migration/thunderbird/src/main/res/values-sr/strings.xml
  feature/onboarding/migration/thunderbird/src/main/res/values-vi/strings.xml
  feature/onboarding/welcome/src/main/res/values-sr/strings.xml
  feature/onboarding/welcome/src/main/res/values-vi/strings.xml
  feature/settings/import/src/main/res/values-sr/strings.xml
  feature/settings/import/src/main/res/values-vi/strings.xml
  feature/widget/message-list/src/main/res/values-vi/strings.xml
  feature/widget/shortcut/src/main/res/values-vi/strings.xml
  feature/widget/unread/src/main/res/values-vi/strings.xml
  legacy/ui/base/src/main/res/values-sr/strings.xml
  legacy/ui/base/src/main/res/values-vi/strings.xml
  legacy/ui/folder/src/main/res/values-co/strings.xml
  legacy/ui/legacy/src/main/res/values-co/strings.xml
  legacy/ui/legacy/src/main/res/values-sr/strings.xml
  legacy/ui/legacy/src/main/res/values-vi/strings.xml
Labels: task: uplift to beta, task: uplift to release

#8659 Change url from raw to api to retrieve the release notes
  .github/workflows/shippable_builds.yml
  scripts/render-notes.py
  scripts/requirements.txt
Labels: task: uplift to release

#8661 Fix skipFtp and packageFormat in publish_release summary
  .github/workflows/shippable_builds.yml
Labels: task: uplift to release

#8658 Add Slovak translation
  app-k9mail/badging/fossRelease-badging.txt
  app-k9mail/badging/fullRelease-badging.txt
  app-k9mail/build.gradle.kts
  app-thunderbird/badging/fossBeta-badging.txt
  app-thunderbird/badging/fossDaily-badging.txt
  app-thunderbird/badging/fossRelease-badging.txt
  app-thunderbird/badging/fullBeta-badging.txt
  app-thunderbird/badging/fullDaily-badging.txt
  app-thunderbird/badging/fullRelease-badging.txt
  app-thunderbird/build.gradle.kts
  legacy/core/src/main/res/values/arrays_general_settings_values.xml
Labels: task: uplift to beta

#8667 [CASA] Fix GitHub actions
  .github/workflows/android.yml
  .github/workflows/codeql.yml
  .github/workflows/gradle-cache.yml
  .github/workflows/markdown.yml
  .github/workflows/needinfo-stale.yml
  .github/workflows/shippable_builds.yml
  .github/workflows/uplift-merges.yml
Labels: type: security, priority: high

#8671 Restart push after app update
  legacy/common/src/main/AndroidManifest.xml
  legacy/core/src/main/java/com/fsck/k9/controller/push/BootCompleteReceiver.kt
Labels: task: uplift to beta, task: uplift to release

#8672 [CASA] Add validation workflows
  .github/workflows/android.yml
  .github/workflows/codeql.yml
  .github/workflows/daily_builds.yml
  .github/workflows/gradle-cache.yml
  .github/workflows/markdown.yml
  .github/workflows/needinfo-remove.yml
  .github/workflows/needinfo-stale.yml
  .github/workflows/scorecard.yml
  .github/workflows/shippable_builds.yml
  .github/workflows/uplift-merges.yml
  .github/workflows/validate-gradle.yml
  .github/workflows/validate-workflows.yml
  scripts/validate-github-actions-pinned.sh
Labels: type: security, priority: high
